### ISSUE TITLE
Outside of world border upon entering Nether

### ISSUE THREAD

**Issue by 01ste02** [Brettflan/WorldBorder#137] opened 2019-05-30 22:00 UTC
Whenever a player teleports into nether from a portal at X:1001175 Z:1002637 into a pre-generated (it was there before the world border was set up) portal, they get teleported to the outer edge of the overworld world border whilst they still remain in nether (they get teleported to 1001175 1002637 plus the radius of the world border). They get a message that they are outside of the world border.

The previously existing portal is located at the previously specified coordinates divided by 8, as it should be. I have tried setting up a world border with it's center at the real portal, but the players only get teleported to the edge of that world border with the same message...

Just to be clear, upon entering nether through the previously existing portal, no new portal is generated. If I turn off the world border in both Nether and the overworld, I get teleported to the old portal as I should be. There is no mention of this event in the logs.

**Comment by TheManchineel** [comment] 2019-06-10 10:46
I can confirm that I have the same issue as you, except/also the other way around. It often leads to death by suffocation or burning too. I made the world borders match like in vanilla now and am also employing the vanilla /worldborder. If you want them different sizes (pretty reasonable) you're better off finding a solution based on MCFunctions until/if this is fixed.

**Comment by Brettflan** [comment] 2019-06-11 01:20
Sounds like the same old Spigot bug (or a very similar one) cropping back up which happened in Spigot 1.9, that they eventually fixed. Old issue created here:
https://github.com/Brettflan/WorldBorder/issues/59

Spigot bug reports:
https://hub.spigotmc.org/jira/browse/SPIGOT-2733
https://hub.spigotmc.org/jira/browse/SPIGOT-1906
https://hub.spigotmc.org/jira/browse/SPIGOT-1903
https://hub.spigotmc.org/jira/browse/SPIGOT-1807

I don't have the time or inclination to look further into it this time around. Feel free to take it up over there:
https://hub.spigotmc.org/jira/projects/SPIGOT/issues

**Comment by Leonardo-Fiori** [comment] 2019-06-19 09:52
Same problem here! Both on latest Spigot version and on Paper 94! When players enter a portal in the overworld that is near to the border, when they come back from the nether using the portal that just spawned, they get teleported well outside the overworld border, then slingshotted back to the center of the map. This very laggy and frustrating for the players, please fix! :(

**Comment by Leonardo-Fiori** [comment] 2019-06-26 09:46
@Brettflan this is not a spigot issue, this does not happen when running a server without the Worldborder plugin :(

**Comment by Brettflan** [comment] 2019-06-26 22:37
> 
> 
> @Brettflan this is not a spigot issue, this does not happen when running a server without the Worldborder plugin :(

Considering this issue doesn't exist in relation to WorldBorder in older versions of MC/Spigot, except when there was a bug in Spigot causing almost the exact same issue that was later fixed in Spigot, you are wrong.

**Comment by Leonardo-Fiori** [comment] 2019-07-01 11:01
> > @Brettflan this is not a spigot issue, this does not happen when running a server without the Worldborder plugin :(
> 
> Considering this issue doesn't exist in relation to WorldBorder in older versions of MC/Spigot, except when there was a bug in Spigot causing almost the exact same issue which was then later fixed in Spigot, you are wrong.

@Brettflan why don't you want to listen to us? Ive tested it, and i have proof that it is caused by world border!

I just expanded the map, now i have set the overworld to 2000 blocks using /wb set 2000.
The nether is set at 250 using /wb set 250.

2000/250 = 8, the magic number for nether portals.

When i go from the nether to the overworld using the same portal that i got teleported to when coming from the overworld, it says: You have reached the edge of this world, and it teleports me far away inside the map!

**AS SOON AS I DISABLE WORLDBORDER**, if i try again to do the same thing with the SAME portals, if i go to the nether it still teleports me to the same (correct) portal, but when i COME BACK, it does not say that i have reached the edge of the world, and it teleports me to a **correct** portal, that is **INSIDE** the edge of the world and near to the one i started from. (The portal in the nether was not exactly at the starting coords / 8 so when it multiplied the coords by 8 it teleported me to a slightly different location, but still correct and inside the 2000 blocks border).


Just say what you want, that is spigot fault, but if i keep your (still awesome) plugin disabled, the nether portals are working correctly. As soon as i enable it, they get screwed up. Think about it.

**Comment by Leonardo-Fiori** [comment] 2019-07-01 11:05
> > @Brettflan this is not a spigot issue, this does not happen when running a server without the Worldborder plugin :(
> 
> Considering this issue doesn't exist in relation to WorldBorder in older versions of MC/Spigot, except when there was a bug in Spigot causing almost the exact same issue which was then later fixed in Spigot, you are wrong.

@Brettflan why don't you want to listen to us? Ive tested it, and i have proof that it is caused by world border!

I just expanded the map, now i have set the overworld to 2000 blocks using /wb set 2000.
The nether is set at 250 using /wb set 250.

2000/250 = 8, the magic number for nether portals.

When i go from the nether to the overworld using the same portal that i got teleported to when coming from the overworld, it says: You have reached the edge of this world, and it teleports me far away inside the map!

**AS SOON AS I DISABLE WORLDBORDER**, if i try again to do the same thing with the SAME portals, if i go to the nether it still teleports me to the same (correct) portal, but when i COME BACK, it does not say that i have reached the edge of the world, and it teleports me to a **correct** portal, that is **INSIDE** the edge of the world and near to the one i started from. (The portal in the nether was not exactly at the starting coords / 8 so when it multiplied the coords by 8 it teleported me to a slightly different location, but still correct and inside the 2000 blocks border).


Just say what you want, that is spigot fault, but if i keep your (still awesome) plugin disabled, the nether portals are working correctly. As soon as i enable it, they get screwed up. Think about it.


P.s. i reported it to spigot and they said that the problem is caused by the WorldBorder plugin

**Comment by Brettflan** [comment] 2019-07-01 12:02
> @Brettflan why don't you want to listen to us? Ive tested it, and i have proof that it is caused by world border!

Because you apparently don't understand. I'm not arguing that the problem occurs when using WorldBorder and doesn't (generally) occur when not using WorldBorder. I'm saying that the root cause is a Spigot bug.

Something similar occurred once before for a few months due to a Spigot bug which was returning mismatched and incorrect location data. They fixed that bug (which I referenced above), and there were no such problems any longer.

Now this problem has popped back up in the latest versions of Spigot, with nothing in WorldBorder having been changed which could have caused it.

Therefore, you might understand why I do not at all believe that it is a problem with WorldBorder. If you don't, then don't be surprised that I don't bother responding to you any further.

**Comment by Leonardo-Fiori** [comment] 2019-07-01 12:09
> > @Brettflan why don't you want to listen to us? Ive tested it, and i have proof that it is caused by world border!
> 
> Because you apparently don't understand. I'm not arguing that the problem occurs when using WorldBorder and doesn't (generally) occur when not using WorldBorder. I'm saying that the root cause is a Spigot bug.
> 
> Something similar occurred once before for a few months due to a Spigot bug which was returning mismatched and incorrect location data. They fixed that bug (which I referenced above), and there were no such problems any longer.
> 
> Now this problem has popped back up in the latest versions of Spigot, with nothing in WorldBorder having been changed which could have caused it.
> 
> Therefore, you might understand why I do not at all believe that it is a problem with WorldBorder. If you don't, then don't be surprised that I don't bother responding to you any further.

So you are saying that the world border bug exists, but it is caused by spigot, right?
I thought that you were saying that the bug did not even exists, and it was just a spigot bug.

Now it makes more sense. But what can we do? I tried to report this as a spigot bug and they closed it telling me that it wasnt.

Actually don't know how to proceed, and players are just getting mad.. and me too, sorry for yelling here on github but i did not get the point.

**Comment by totemo** [comment] 2019-08-06 10:16
Looks like a duplicate of #131.

**Comment by Brettflan** [comment] 2020-01-13 00:09
It looks like they finally fixed it:
https://hub.spigotmc.org/jira/browse/SPIGOT-5252

So it should hopefully be handled in the next Spigot release.

**Closed by Brettflan** 2020-01-13 00:09 UTC
