### ISSUE TITLE
Wayback Nether portal problems

### ISSUE THREAD

**Issue by Leonardo-Fiori** [Brettflan/WorldBorder#144] opened 2019-06-19 10:00 UTC
I'm not the only one here having this problem..

when players go to the nether using a portal that is near the overworld border, they get teleported correctly to the nether. But when they use the portal that has just spawned in the nether to get back to the overworld, they get teleported wayy beyond the overworld border, and then slingshotted back to the center of the map, causing lots of lag (and angery)

Happening both on latest version of spigot and paper

Then there is another problem. If you expand the overworld border and then to a /fill, worldborder fails to fill a "ring" of chunks just after the original map size.. another player reported this on the spigot forums, he made a screenshot. I did forget to make a screenshot and proceeded filling the chunks manually by flying over them. Here is the screenshot:
https://proxy.spigotmc.org/bcf716a501192b862c8d2d85e72f8e546286d375?url=https%3A%2F%2Fi.imgur.com%2FLqiWadN.png

**Comment by thunderlight411** [comment] 2019-06-20 19:16
Can confirm this with build 1.9.10(beta) and paper build git-paper-96

**Comment by Leonardo-Fiori** [comment] 2019-06-20 19:21
> Can confirm this with build 1.9.10(beta) and paper build git-paper-96

Yeah lots of people are reporting this bug, author is not responding :(

**Comment by DalBrar** [comment] 2019-06-22 00:42
Bugs with teleporting from nether to overword via Portals...
Say world border for WORLD is set to 20,000 radius and 2500 for NETHER.

Bug 1:
Portal in Nether at 2490, 2490 takes player to 2490, 2490 in WORLD and displays "you have reached edge of the world message".

Bug 2:
Not if you increase NETHER radius to 3000 and build portal at 2800, 2800 with WORLD border still 20,000. Teleports player to 0, 64, 0 (not my world spawn).

**Comment by roopekoo** [comment] 2019-06-23 10:56
@Leonardo-Fiori I was the original poster of the image that image. I have created new issue #145 it has the whole map rendered and the map has these squares quite often as the distance from the spawn increases.

**Comment by Leonardo-Fiori** [comment] 2019-06-26 09:43
@Brettflan , where are you!

**Comment by Leonardo-Fiori** [comment] 2019-07-01 11:07
Im posting also here, to keep this issue updated. The original post is from another similar issue, to which @Brettflan answered that it is spigot fault, and not worldborder's fault. This is the proof that he is wrong.

I just expanded the map, now i have set the overworld to 2000 blocks using /wb set 2000.
The nether is set at 250 using /wb set 250.

2000/250 = 8, the magic number for nether portals.

When i go from the nether to the overworld using the same portal that i got teleported to when coming from the overworld, it says: You have reached the edge of this world, and it teleports me far away inside the map!

AS SOON AS I DISABLE WORLDBORDER, if i try again to do the same thing with the SAME portals, if i go to the nether it still teleports me to the same (correct) portal, but when i COME BACK, it does not say that i have reached the edge of the world, and it teleports me to a correct portal, that is INSIDE the edge of the world and near to the one i started from. (The portal in the nether was not exactly at the starting coords / 8 so when it multiplied the coords by 8 it teleported me to a slightly different location, but still correct and inside the 2000 blocks border).

Just say what you want, that is spigot fault, but if i keep your (still awesome) plugin disabled, the nether portals are working correctly. As soon as i enable it, they get screwed up. Think about it.

P.s. i reported it to spigot and they said that the problem is caused by the WorldBorder plugin

**Comment by thunderlight411** [comment] 2019-07-01 11:21
i have seen that when i activate worldborder bypass the portals are working without any problem

**Comment by Leonardo-Fiori** [comment] 2019-07-01 11:29
> i have seen that when i activate worldborder bypass the portals are working without any problem

Of course, but players then are allowed to walk beyond the border.. so whats the point of this plugin then? :(

**Comment by JonMagon** [comment] 2019-07-04 05:27
The same problem.

**Comment by JonMagon** [comment] 2019-07-05 15:53
@thunderlight411 @DalBrar please check https://github.com/Brettflan/WorldBorder/issues/145#issuecomment-508754868

**Comment by thunderlight411** [comment] 2019-07-05 20:41
Thnx @JonMagon going to check and test it out

**Comment by JonMagon** [comment] 2019-07-08 13:16
The problem isn't at all with nethers portals. It's issue with all world-to-world teleportations. I've disabled all teleportation events and it works good. Not final solution, but for a while now.

[WorldBorder-JonMagon_fork0.2.zip](https://github.com/Brettflan/WorldBorder/files/3368475/WorldBorder-JonMagon_fork0.2.zip)

**Comment by JohnS19** [comment] 2019-07-26 22:05
Any news on a fix?

**Comment by Leonardo-Fiori** [comment] 2019-07-26 23:05
@JohnS19 for now just enable worldborder when you need to fill/trim then use vanilla wolrd border

**Comment by totemo** [comment] 2019-08-06 10:16
Looks like a duplicate of #131.

**Comment by Brettflan** [comment] 2020-01-13 00:13
It looks like they finally fixed it:
https://hub.spigotmc.org/jira/browse/SPIGOT-5252

So it should hopefully be handled in the next Spigot release.

**Closed by Brettflan** 2020-01-13 00:13 UTC
