### ISSUE TITLE
Portals considering wrong dimension border

### ISSUE THREAD

**Issue by TheManchineel** [Brettflan/WorldBorder#140] opened 2019-06-10 10:52 UTC
My main Overworld "world" border radius is 5000 blocks, while the Nether "world_nether" has a border radius of 625 (5000/8). Traveling from the Overworld to the Nether using portals works perfectly, though whenever I try to cross an Overworld portal in the Nether, if it's located at an X or Z Nether coordinate past 625/8 (about 78 blocks) for some reason I get teleported to the Overworld at either X or Z equal to 625 (depending on which axis the OW portal in the Nether was past 78) and same Y as previously. Needless to say most of the time this leads to death/suffocation of the player.

What seems to be happening is that the portal is knocking players back in the overworld following the world border set for the wrong world (world_nether instead of world).

Here is my config.yml

```
cfg-version: 11
message: You have reached the Border of this world!
round-border: false
debug-mode: false
whoosh-effect: true
portal-redirection: false
knock-back-dist: 3.0
timer-delay-ticks: 5
remount-delay-ticks: 0
dynmap-border-enabled: true
dynmap-border-message: World Border
dynmap-border-hideByDefault: false
dynmap-border-priority: 0
player-killed-bad-spawn: false
deny-enderpearl: true
fill-autosave-frequency: 30
bypass-list-uuids: []
fill-memory-tolerance: 500
prevent-block-place: false
prevent-mob-spawn: false
worlds:
  world:
    x: 0.0
    z: 0.0
    radiusX: 5000
    radiusZ: 5000
    wrapping: false
  world_nether:
    x: 0.0
    z: 0.0
    radiusX: 5000
    radiusZ: 5000
    wrapping: false
  world_the_end:
    x: 0.0
    z: 0.0
    radiusX: 5000
    radiusZ: 5000
    wrapping: false
```

I'm using PaperMC 1.14.2 with the following plugins: Copy-Coords*, CoreProtect, CustomMOTD*, DiscordSRV, LuckPerms, ViaVersion*, WorldBorder
Server version: "This server is running Paper version git-Paper-55 (MC: 1.14.2) (Implementing API version 1.14.2-R0.1-SNAPSHOT)"

**Comment by Venaf** [comment] 2019-06-16 10:49
I'm getting this same issue, it seems like it's moving players based on the nether border instead of the overworld border when travelling from nether to overworld.

**Comment by Leonardo-Fiori** [comment] 2019-06-19 09:55
Same issue here. Not sure if my nether is actually 8 times smaller than the overworld but i am going to trim it just in case. However on the wayback from the nether players get slinghsotted back to the center of the map causing a lot of lag. And they get the out of border message..

**Comment by totemo** [comment] 2019-08-06 10:16
Looks like a duplicate of #131.

**Comment by yourfate** [comment] 2019-08-12 18:19
Yup, same issue here.

**Comment by Brettflan** [comment] 2020-01-13 00:11
It looks like they finally fixed it:
https://hub.spigotmc.org/jira/browse/SPIGOT-5252

So it should hopefully be handled in the next Spigot release.

**Closed by Brettflan** 2020-01-13 00:11 UTC
